### ISSUE TITLE
Is MRG revision needed for resolving TermRefs?

### ISSUE THREAD

**Issue by RieksJ** [tno-terminology-design/tev2-specifications#11]
Playing around a little with my toy-mrgt, it occurred to me that MRG-entries may not have sufficient data for accommodating all necessary varieties for converting TermRefs, as is done by the TRRT. This issue wants to make sure that this gets checked and corrected if needed.

Note that an MRG-entry can be used:
- in a context of the scope that curates it, e.g.,
  - for development. In this case, paths are local, and predominantly relative
  - for production. In this case, paths typically point to a server, a directory on the server, and whatever it is that needs to be referred to.
- in a context of a scope that imports it. Would that I would say that this would be simil

The following list specifies the kinds of data that an MRG-entry must contain for proper TermRef conversions of various kinds, that cannot (or should not) be solved by specifying fields in CText front-matter (as is done, e.g., for `glossaryText` and `hoverText`). 

We need data to be available to
1. construct a link to the renderable version of the CText associated with the TermRef
2. construct a link to the file on a github or gitlab repo where the CText lives
3. ... (anything else)?

The current specs say we have the following data available in the MRG:
1. the `scopetag` in an mrg-entry, which is said to refer to the scope in which the entry is curated. This is problematic, as there is no good way to derefernce the scopetag to the associated scopedir, because the entry could be an import of an import of an import.
2. `locator`, i.e. path, relative to some scopedir/curatedir/ where the curated text lives. This has similar problems for 'foreign' scopes. It should be (a tag that can be dereferenced within the MRG itself, that points to) a full path of where the curated text lives.
3. `navurl`, i.e. path, relative to the website url, where the rendered version of the curated text lives. Again, for 'foreign' scopes this can be problematic.

Question: what stuff do we need?

Suggestions for changes:
1. replace the `scopetag` in an mrg-entry either with the scopedir of the scope in which it is curated, or a simple sequence number that maps to the scopedir in the `scopes` section of the MRG.
2. ...

**Comment by Ca5e** [comment]
I'm not sure if replacing the `scopetag` in an mrg-entry with something more elaborate would help. A MRG should already mention the scopedirs of the accommodating scopes in its scopes section. 
As the TRRT doesn’t use external SAFs, the `website` property in it can’t be used. It thus might be useful to make the `navurl` of an entry a fully resolved url. The `locator` should be relative to the ‘scopedir’ and not the ‘curatedir’, as the `curatedir` information also isn’t accessible from an external scope.

I think I will have a better understanding of what certain changes will do when an initial new MRGT is created.

**Comment by RieksJ** [comment]
Dit lijkt te zijn gebeurd. Bij nieuwe problemen moet er maar een neiuwe issue gemaakt worden
