### ISSUE TITLE
BREAKING CHANGE: termselcrit --> termselection

### ISSUE THREAD

**Issue by RieksJ** [tno-terminology-design/tev2-specifications#17]
The phrases `termselcrit` and `term selection criteria` really don't mean what they suggest; they are not criteria, but rather instructions for adding stuff to a terminology-under-construction.

As a result, the `termselcrit` field in the `versions` section in the SAF has been renamed into `termselection`. @RieksJ will change most (if not all) SAFs).

This means that all existing SAFs must accommodate for these changes, and also the MRGT must take this change into account.

@Ca5e : please close this issue when you have accommodated this change in the MRGT.

**Comment by RieksJ** [comment]
@Ca5e I just might have covered it all, pls check

**Comment by Ca5e** [comment]
The change will be reflected in the MRGT when v0.1.3 is published.
