### ISSUE TITLE
TRRT corrupts links

### ISSUE THREAD

**Issue by RieksJ** [tno-terminology-design/tev2-specifications#20]
When I run the TEv2-specifications site on localhost, everything works well. However, when it is generated to work on github.io, normal markdown links get corrupted. Looking at the HTML contents of the page you can see that termrefs are not properly created, but extend way too far, as illustrated in the figure below:

![image](https://github.com/tno-terminology-design/tev2-specifications/assets/8522589/fa049923-8934-44b3-a08a-cf3b41650e8f)

This should, of course, be fixed.

**Comment by Ca5e** [comment]
I am not sure why, but not using a blank line before the start of the first list item seems to cause issues when any html tags are used in markdown. As you can see below, the markdown hyperlink syntax is only seen when a newline is added. I don't think the TRRT or Docusaurus can do anything about this, it seems to be a markdown thing. 

https://github.com/tno-terminology-design/tev2-specifications/assets/6130478/d8108a4b-aed0-4bc0-866f-db9979a7e387

**Comment by RieksJ** [comment]
OK. Officially, a markdown list should have an empty line in front of it. I've never seen that not abiding by this convention ever had any real effect, until now... I've changed all other occurrenaces of lists without an empty line, so that they now do have a preceeding empty line.
