### ISSUE TITLE
Make 'scopetags' section in SAF simpler

### ISSUE THREAD

**Issue by RieksJ** [tno-terminology-design/tev2-specifications#8]
It may be simpler to change the `scopetags`-field, which is currently a list of scopetags, into a `scopetag`-field, which would specifiy a single scopetag. This would encourage curators to use no more than one scopetag for each scope they refer to, but if they really wanted to, they could make multiple entries with different scopetags that refer to the same scopedir.

**Comment by Ca5e** [comment]
Implemented already.
